### ISSUE TITLE
Custom data type converters

### ISSUE THREAD

**Issue by dlaidlaw** [BryanHunt/mongo-emf#10]
The plugin already handles all the native mongo database data types, however, it is sometimes required to have customer converters to convert types or objects to/from mongo storage. For example the java.util.Calendar class (and therefore java.util.GregorianCalendar) is not handled by mongo natively, but it still needs to be stored. Some my want to store it as a long value, others as an ISO8601 string. Providing a custom data type conversion mechanism will enable the user of the plugin to decide how data is stored in mongo.

**Comment by BryanHunt** [comment]
Here's my first attempt at an API.

public interface IMongoEmfConverter
{
    Object convertMongoDBValueToEMFValue(Object databaseValue);

```
Object convertEMFValueToMongoDBValue(Object emfValue);
```

}

I still need to sort out how to register the converter.

**Comment by BryanHunt** [comment]
Second attempt at an API.

public interface IMongoEmfConverter
{
    Object convertMongoDBValueToEMFValue(Object databaseValue);

```
Object convertEMFValueToMongoDBValue(Object emfValue);

boolean isConverterForType(EDataType type);
```

}

I'm thinking the algorithm will be to iterate over the converters asking each isConverterForType().  This would allow a converter to operate on a base class if needed.  The last converter in the list would be the default that calls EcoreUtil.convertToString(eDataType, rawValue).

**Comment by BryanHunt** [comment]
Revised API ...

public interface IMongoEmfConverter
{
    Object convertMongoDBValueToEMFValue(EDataType eDataType, Object databaseValue);

```
Object convertEMFValueToMongoDBValue(EDataType eDataType, Object emfValue);

boolean isConverterForType(EDataType type);
```

}

**Comment by BryanHunt** [comment]
I pushed the implementation for this to master.  Please have a look when you get a minute.  Converters are added using MongoDBURIHandlerIimpl.addConverter().
