### ISSUE TITLE
Enabling on-demand loading for large collections

### ISSUE THREAD

**Issue by gggard** [BryanHunt/mongo-emf#16]
When a InputStream is created (in MongoInputStream) with a query on the URI, all the collection is loaded at ressource creation time (line 93-94), which can be long in case of a query returning huge amount of elements.

With huge (several milions of elements), the EList performances are very poor (and not linear).

It would be nice to delegate this to the QueryEngine in order to permit a on demand load of the collection with eventual caching.

Thanks in advance for your comments and eventually proposals

**Comment by BryanHunt** [comment]
Are you looking for something similar to a cursor object where the elements are not loaded until you iterate using the cursor?

I've looked into doing some caching, and it is going to requires some changes to EMF.  I've discussed this a bit with Ed, but we both seem to be too busy to work through the issues.  I hope to get back to working on the caching soon.

**Comment by gggard** [comment]
Thanks for the answer, my comments bellow :

Yes basically it is certainly the solution when the collection become huge (which is the main reason to use Mongo), I do not know if it is a heavy modification of EMF or a modification of your EMF query package.

I managed to implement a quick and dirty solution do that by redefining in the emf.query model a CursorBasedResult type   having as super type Result then the values attributes of this Class is not a EObjectResolvingEList EList but a Mango oriented list (which rely on the Mango cursor mechanism). There is some modifications here and there to initialise the Result object passing the query to it (and delegating the query processing to it) but globally it seams to work.

I agree that it is not perhaps the most elegant (and EMF spirit oriented) solution but it permit to gain a huge factor on performances.

Concerning caching, once we have this smart result object, depending on the operation performed on the list (using iterator or direct access to the components using get(X)), a caching mechanism can be implemented in the list asking to Mango more results that are actually needed and trying to guess what will be the next requests.

**Comment by tigergui1990** [comment]
Hi,
This feature is real in our plan, in our new XText [based query engine](https://github.com/tigergui1990/MongoEMF-query-engine/wiki/XText-based-query-engine-for-MongoEMF-project-proposal), we will use SQL to query data from MongoDB, and we will support select _special_ several columns from collection. For example, we can use  SQL "select z from things where x="john" " to represent MongoDB command "db.things.find( { x : "john" }, { z : 1 } );" in the future

**Comment by tigergui1990** [comment]
You guys can get the design details and demo code of this new "Retrieving a Subset of Fields" support search engine here https://github.com/tigergui1990/MongoEMF-query-engine/wiki/XText-based-query-engine-for-MongoEMF-project-proposal

**Comment by BryanHunt** [comment]
Just to be clear ... I believe this issue is more about retrieving objects on demand when the results returned from a query contain many objects and not about retrieving a subset of fields.

**Comment by tigergui1990** [comment]
Yeah, you are right. I just think return a subset of fields rather than the whole document can also improve data transmission performance. Anyway, performance is the key word concerned here, so i post that comment here :-)

**Comment by BryanHunt** [comment]
I think creating a cursor would be fairly straight forward.  Something like:

public class MongoCursor extends EObjectImpl implements Iterable<EObject>

**Comment by tigergui1990** [comment]
Yeah, i will survey some exist cursor products and try to find a clear solution.

**Comment by BryanHunt** [comment]
I think the solution is outside of the query engine.  I think I can make a simple modification to the MongoInputStream and provide a cursor.

**Comment by BryanHunt** [comment]
I added a MongoCursor that implements Iterable<EObject>.  To have a MongoCursor returned instead of a Result from a query, set the load option MongoURIHandlerImpl.OPTION_QUERY_CURSOR to Boolean.TRUE

Implemented in commit 757a3e35d37ab68ab9ea6851746de0e6220648da

**Comment by tigergui1990** [comment]
Nice :-)

**Comment by gggard** [comment]
Many thanks Bryan ! 
We will try it during this week

**Comment by BryanHunt** [comment]
Another thing that will greatly help with loading a large number of objects is using MongoResourceSetImpl instead of ResourceSetImpl.  I'll be doing a blog post on this soon.  The performance graph is shocking.
