### ISSUE TITLE
Refactor IQueryEngine to support field selection

### ISSUE THREAD

**Issue by jconlon** [BryanHunt/mongo-emf#22]
More advanced query languages provide the ability to select which fields in a document are returned from a MongoDB query.

Currently the IQueryEngine provides a return type of  DBObject.   This is sufficient to find documents in a collection, with DBCollection.find(DBObject ref)  but in order to select which fields of the documents are returned a second DBObject must be returned - DBCollection.find(DBObject ref, DBObject fields).  

Change IQueryEngine  to support returning a second DBObject.  

This will affect the client usage of IQueryEngine in the MongoInputStream class.

**Comment by BryanHunt** [comment]
Changes pushed to master
