### ISSUE TITLE
Doesn't build

### ISSUE THREAD

**Issue by njbartlett** [BryanHunt/mongo-emf#5]
Plugin org.eclipselabs.mongo requires version 2.6.3 of com.mongodb:

```
Require-Bundle: com.mongodb;bundle-version="2.6.3"
```

But the version of com.mongodb from the workspace is 2.5.2:

```
Bundle-SymbolicName: com.mongodb
Bundle-Version: 2.5.2
```

Which should it be? And shouldn't you use Import-Package anyway instead of Require-Bundle?

**Comment by merks** [comment]
Bryan,

I'm not sure what Neil means by "the version from the workspace"...

Regards,
Ed

**Comment by BryanHunt** [comment]
Fixed pushed to master

**Comment by BryanHunt** [comment]
I didn't put a version on the import package - the code doesn't compile when I set the minimum version to 2.7.0 even though I have that driver version in my target platform.  The code should work with just about any driver version.

**Comment by njbartlett** [comment]
Ed: I mean the version that's... in the workspace. The source repository contains a "com.mongodb" project under "bundles". Or should I not import that into the Eclipse workspace as a project?

It would be really great if the checkout/build instructions could be updated, they don't seem to reflect the current state. Cheers!

**Comment by BryanHunt** [comment]
The MongoDB driver source was included in this repo mainly for convenience while developing.  The driver code is out of date and should be deleted.  The MongoDB driver should be picked up from the official downloads.  I'll try to update the wiki soon.
