### ISSUE TITLE
Add support for EMF ID attribute

### ISSUE THREAD

**Issue by BryanHunt** [BryanHunt/mongo-emf#6]
It would be nice to support the EMF ID attribute.  If the ID flag is set on an attribute, then map the value of that attribute to the MongoDB _id key.  Consideration needs to be given to the query engine since it would have to map the ID atribute name to _id.

**Comment by merks** [comment]
Bryan,

An ID is only unique per resource.  I suppose in Mongo it needs to be 
unique across the entire collection, right?

**Comment by BryanHunt** [comment]
Ed,

Correct, the ID must be unique across the entire collection.  If we add this capability, it would be up to the user to ensure uniqueness.  This capability comes from a request in a comment on my blog post.

**Comment by BryanHunt** [comment]
I started looking at the code to support this feature and quickly realized that the query engine does not know the EClass when parsing the query and therefore cannot substitute the ID attribute name with _id.  I would propose that we write the ID attribute value to both _id and the attribute name with a save option to not use the attribute name.  This would allow clients to query by attribute name in the default case, and when using the save option, clients would be required to query by _id.

**Comment by merks** [comment]
What's the advantage of using _id?  Maybe _id should only be used for 
extrinsic IDs, i.e., IDs managed by the resource rather than as a 
feature on the instance?

**Comment by BryanHunt** [comment]
MongoDB requires the presence of _id.  If _id is not specified as a field when inserting a record, MongoDB will automatically generate the _id as an ObjectId.  We already support Extrinsic IDs using _eId.

**Comment by merks** [comment]
I see.  So the main point is to keep it from generating a useless ID.

**Comment by BryanHunt** [comment]
Yes, MongoDB generated ID's may be more efficient, but they aren't very user friendly.  We already support user specified id's in the URI, but you have to know to supply the ID in the URI when adding a new object (this is not very RESTful).  Tying this to the ID attribute would seem to be a natural fit.  The user could then POST to http://host/db/objects/ an object with a "name" ID attribute and then subsequently access the object with the URI http://host/db/objects/name

**Comment by BryanHunt** [comment]
I've added OPTION_USE_ID_ATTRIBUTE_AS_PRIMARY_KEY as a save option.  If it is set to Boolean.TRUE and the ID was not specified in the URI, the value of the ID attribute will be used as the MongoDB _id if it exists.  If this is acceptable, I'll commit the changes.

**Comment by merks** [comment]
Bryan,

That sounds good.

**Comment by dlaidlaw** [comment]
This looks great!

Thanks.

**Comment by BryanHunt** [comment]
Changed pushed to master
